### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by fergusq** [BikkuMyy/robolabra#1]
Ohjelmasi vaikuttaa edistyvän hyvin! Luin raportit ja muut dokumentit ja niiden perusteella olet käyttänyt paljon aikaa ohjelman ja robotin suunnitteluun. Ideasi on ollut alusta asti selkeä, mikä lienee edesauttanut nopeaa etenemistä.

Minulla ei ole Lego-robottia, joten en päässyt kääntämään ohjelmaa ja testaamaan sitä. En tiedä oliko se tarkoituskaan, vaikka ohjeissa puhuttiin siitä. Arvioin tässä koodin luettavuutta.

Ohjelmasi rakenne ja luokkajako on hyvä. Minulla on joitakin parannusehdotuksia, jotka voisivat kehittää koodin luettavuutta.

Hyvää nimeämistapaa olisi hyvä noudattaa. Sinulla on joitain lyhennenimiä (`m1`, `ts`, `ls`), joiden merkitykset ovat epäselvät. Suosittelen käyttämään kokonaisia sanoja, kuten `motor1` ja `touchSensor`.

Jokaisen metodin nimessä olisi hyvä olla verbi, joka ilmaisee metodin luonteen. BeltController-luokan metodit on nimetty hyvin. ColorReader-luokassa on nyt kuitenkin hyvin hämäävästi nimettyjä metodeja:

* Booleanin palauttavat metodit nimetään Javassa usein "is"-verbin avulla. `readable()` olisi siis paremmin `isReadable()`.
* Nimestä `value()` ei voi päätellä, palauttaako metodi arvon vai ei. Itse olisin veikannut ensimmäistä. Nimi olisi paremmin `printValue()`.
* Nimi `greaterThanDivider()` antaa ymmärtää, että metodi palauttaa booleanin, kuten `readable`. Se ei kuitenkaan tee tätä vaan tulostaa koodia ilmeisesti testaustarkoituksissa. Sen nimi voisi olla `printDebugInfo()` tai `printCurrentState()` tms. Jos metodin tarkoitus olisi palauttaa boolean, nimi voisi olla `isGreaterThanDivider()`.

`greaterThanDivider()`-metodin JavaDocissa pitäisi myös mainita, että se tulostaa jotain.

Vielä huomautus Gitin käytöstä: älä laita class-tiedostoja gittiin; jokainen lataaja voi kääntää ne halutessaan. Lisää siis .gitignoreen `bin/`.

Kirjoitin arvion sen perusteella, mitä koodi oli 7.1.

**Comment by BikkuMyy** [comment]
Kiitos, tästä oli paljon hyötyä!
